Repository Team-Puzzling/Puzzling_Android, pull requests merged in 2023-07, with the labels that each got.

#6 [FEAT] 회고 작성 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/puzzling/puzzlingaos/base/BaseDialogFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/base/BottomSheetDialogFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/ChooseRetrospectiveFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/RegisterDialogFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/WriteRetrospectiveActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/WriteRetrospectiveViewModel.kt
  app/src/main/res/drawable/circle_blue400_fill.xml
  app/src/main/res/drawable/circle_gray300_line.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_down.xml
  app/src/main/res/drawable/img_dialog_puzzle.png
  app/src/main/res/drawable/rect_bg50_fill_radius_16.xml
  app/src/main/res/drawable/rect_blue400_fill_radius_16.xml
  app/src/main/res/drawable/rect_gray300_fill.xml
  app/src/main/res/drawable/rect_white_fill_top16.xml
  app/src/main/res/drawable/selector_custom_button.xml
  app/src/main/res/drawable/selector_custom_edittext.xml
  app/src/main/res/layout/activity_write_retrospective.xml
  app/src/main/res/layout/fragment_choose_retrospective.xml
  app/src/main/res/layout/fragment_register_dialog.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/text_appearance.xml
  app/src/main/res/values/themes.xml
Labels: 지영🥭

#9 [FEAT] 초대코드 입력 뷰 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/puzzling/puzzlingaos/data/model/response/ResponseInvitationCodeDto.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/main/invitationCode/InputCodeFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/main/invitationCode/InputProfileFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/main/invitationCode/InvitationCodeActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/main/invitationCode/InvitationCodeViewModel.kt
  app/src/main/res/drawable/ic_cancel.xml
  app/src/main/res/drawable/ic_puzzling_logo.png
  app/src/main/res/drawable/rect_blue200_line_16.xml
  app/src/main/res/drawable/rect_blue400_fill_16.xml
  app/src/main/res/drawable/rect_gray050_fill_16.xml
  app/src/main/res/drawable/rect_gray400_fill_16.xml
  app/src/main/res/drawable/rect_red200_line_16.xml
  app/src/main/res/drawable/sel_invitation_background_edittext.xml
  app/src/main/res/layout/activity_invitation_code.xml
  app/src/main/res/layout/fragment_input_code.xml
  app/src/main/res/layout/fragment_input_profile.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 가은🍊

#13 [FEAT] 대시보드 퍼즐뷰 구현
  app/src/main/java/com/puzzling/puzzlingaos/base/BaseFragment.kt
  app/src/main/res/drawable/ic_next.xml
  app/src/main/res/drawable/img_home_puzzle_btn.png
  app/src/main/res/drawable/img_puzzle1.png
  app/src/main/res/drawable/img_puzzle10.png
  app/src/main/res/drawable/img_puzzle11.png
  app/src/main/res/drawable/img_puzzle12.png
  app/src/main/res/drawable/img_puzzle13.png
  app/src/main/res/drawable/img_puzzle14.png
  app/src/main/res/drawable/img_puzzle15.png
  app/src/main/res/drawable/img_puzzle2.png
  app/src/main/res/drawable/img_puzzle3.png
  app/src/main/res/drawable/img_puzzle4.png
  app/src/main/res/drawable/img_puzzle5.png
  app/src/main/res/drawable/img_puzzle6.png
  app/src/main/res/drawable/img_puzzle7.png
  app/src/main/res/drawable/img_puzzle8.png
  app/src/main/res/drawable/img_puzzle9.png
  app/src/main/res/drawable/rect_white_fill_radius_16.xml
  app/src/main/res/layout/fragment_jy_team_dashboard.xml
  app/src/main/res/layout/fragment_personal_dashboard.xml
  app/src/main/res/layout/item_personal_puzzle.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/text_appearance.xml
Labels: 지영🥭

#15 [FEAT] 프로젝트 등록 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/puzzling/puzzlingaos/data/repository/RegisterRepositoryImpl.kt
  app/src/main/java/com/puzzling/puzzlingaos/data/source/remote/RegisterRemoteDataSource.kt
  app/src/main/java/com/puzzling/puzzlingaos/domain/entity/RetrospectWeekCycle.kt
  app/src/main/java/com/puzzling/puzzlingaos/domain/repository/RegisterRepository.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/register/DatePickerFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/register/RegisterActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/register/RegisterViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/register/RetrospectWeekCycleAdapter.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/team/currentSituation/TeamCurrentSituationFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/util/ViewModelFactory.kt
  app/src/main/res/drawable/bg_register_date_background.xml
  app/src/main/res/drawable/bg_register_daycycle.xml
  app/src/main/res/drawable/bg_register_edit_background.xml
  app/src/main/res/drawable/bg_register_registerbutton_deselect.xml
  app/src/main/res/drawable/bg_register_registerbutton_select.xml
  app/src/main/res/drawable/ic_my_toolbar_alarm.xml
  app/src/main/res/drawable/ic_my_toolbar_back.xml
  app/src/main/res/drawable/ic_register_day_dropdown.xml
  app/src/main/res/drawable/ic_register_toolbar_close.xml
  app/src/main/res/drawable/rect_blue_fill_16.xml
  app/src/main/res/drawable/rect_red_line_16.xml
  app/src/main/res/drawable/sel_register_drawable_custom_edittext.xml
  app/src/main/res/drawable/sel_register_drawable_enabled_btn.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/fragment_date_picker.xml
  app/src/main/res/layout/fragment_team_current_situation.xml
  app/src/main/res/layout/item_register_retrospect_week_cycle.xml
  app/src/main/res/values/strings.xml
Labels: 민정🍑

#18 [FEAT] 홈 대시보드 뷰 UI 상세화
  app/src/main/java/com/puzzling/puzzlingaos/data/model/response/ResponseActionPlanDto.kt
  app/src/main/java/com/puzzling/puzzlingaos/data/model/response/ResponseProceedingProjectDto.kt
  app/src/main/java/com/puzzling/puzzlingaos/data/model/response/ResponseTeamRankingDto.kt
  app/src/main/java/com/puzzling/puzzlingaos/domain/entity/ActionPlan.kt
  app/src/main/java/com/puzzling/puzzlingaos/domain/entity/TeamRanking.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/HomeFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/JyTeamDashboardFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/PersonalDashboardFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/personal/ActionPlanListAdapter.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/personal/PersonalDashboardFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/personal/PersonalDashboardViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/team/TeamDashBoardViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/team/TeamDashboardFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/WriteRetrospectiveActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/WriteRetrospectiveViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/util/DividerItemDecoration.kt
  app/src/main/java/com/puzzling/puzzlingaos/util/IntentExt.kt
  app/src/main/res/drawable/ic_first_rank.xml
  app/src/main/res/drawable/ic_puzzle.xml
  app/src/main/res/drawable/ic_second_rank.xml
  app/src/main/res/drawable/ic_third_rank.xml
  app/src/main/res/drawable/img_puzzle11.png
  app/src/main/res/drawable/rect_blue_fill_radius_16_gradient.xml
  app/src/main/res/drawable/rect_lightblue_fill_radius_14_gradient.xml
  app/src/main/res/drawable/shape_bottomnavi_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_jy_team_dashboard.xml
  app/src/main/res/layout/fragment_personal_dashboard.xml
  app/src/main/res/layout/fragment_team_dashboard.xml
  app/src/main/res/layout/item_home_actionplan.xml
  app/src/main/res/values/strings.xml
Labels: 지영🥭

#29 [FEAT] 홈 뷰 디테일 UI 구현
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/team/TeamDashBoardViewModel.kt
Labels: 지영🥭

#30 [FEAT] 회고 작성뷰 detail 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/puzzling/puzzlingaos/base/BindingAdapter.kt
  app/src/main/java/com/puzzling/puzzlingaos/domain/entity/ActionPlan.kt
  app/src/main/java/com/puzzling/puzzlingaos/domain/entity/PuzzleBoard.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/HomeFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/HomeViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/personal/MyPuzzleBoardActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/personal/MyPuzzleBoardAdapter.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/personal/MyPuzzleBoardViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/personal/PersonalDashboardFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/personal/PersonalDashboardViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/team/TeamDashBoardViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/team/TeamDashboardFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/team/TeamPuzzleBoardActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/team/TeamPuzzleBoardAdapter.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/team/TeamPuzzleBoardViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/main/HomeChooseProjectAdapter.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/main/HomeChooseProjectFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/ChooseRetrospectiveFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/Write5fFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/WriteAarFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/WriteRetrospectiveActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/WriteRetrospectiveViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/WriteTilFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/util/ViewExt.kt
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/img_dialog_puzzle1.png
  app/src/main/res/drawable/img_myboard1.xml
  app/src/main/res/drawable/img_myboard2.xml
  app/src/main/res/drawable/img_myboard3.xml
  app/src/main/res/drawable/img_myboard4.xml
  app/src/main/res/drawable/img_teamboard1.xml
  app/src/main/res/drawable/img_teamboard2.xml
  app/src/main/res/drawable/img_teamboard3.xml
  app/src/main/res/drawable/img_teamboard4.xml
  app/src/main/res/drawable/selector_custom_edittext.xml
  app/src/main/res/layout/activity_my_puzzle_board.xml
  app/src/main/res/layout/activity_team_puzzle_board.xml
  app/src/main/res/layout/activity_write_retrospective.xml
  app/src/main/res/layout/fragment_choose_retrospective.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_choose_project.xml
  app/src/main/res/layout/fragment_personal_dashboard.xml
  app/src/main/res/layout/fragment_register_dialog.xml
  app/src/main/res/layout/fragment_team_dashboard.xml
  app/src/main/res/layout/fragment_write5f.xml
  app/src/main/res/layout/fragment_write_aar.xml
  app/src/main/res/layout/fragment_write_til.xml
  app/src/main/res/layout/item_home_project.xml
  app/src/main/res/layout/item_mypuzzle_board.xml
  app/src/main/res/layout/item_team_board.xml
  app/src/main/res/values/text_appearance.xml
Labels: 지영🥭

#37 [FEAT] 서버통신 세팅
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/puzzling/puzzlingaos/base/BindingAdapter.kt
  app/src/main/java/com/puzzling/puzzlingaos/data/interceptor/ExampleInterceptor.kt
  app/src/main/java/com/puzzling/puzzlingaos/data/model/response/BaseResponse.kt
  app/src/main/java/com/puzzling/puzzlingaos/data/model/response/ResponseActionPlanDto.kt
  app/src/main/java/com/puzzling/puzzlingaos/data/model/response/ResponseMyPuzzleBoardDto.kt
  app/src/main/java/com/puzzling/puzzlingaos/data/model/response/ResponseProceedingProjectDto.kt
  app/src/main/java/com/puzzling/puzzlingaos/data/repository/MyBoardRepositoryImpl.kt
  app/src/main/java/com/puzzling/puzzlingaos/data/service/PersonalReviewService.kt
  app/src/main/java/com/puzzling/puzzlingaos/data/source/remote/MyDashBoardDataSource.kt
  app/src/main/java/com/puzzling/puzzlingaos/data/source/remote/impl/MyDashBoardDataSourceImpl.kt
  app/src/main/java/com/puzzling/puzzlingaos/di/ApiModule.kt
  app/src/main/java/com/puzzling/puzzlingaos/di/DataSourceModule.kt
  app/src/main/java/com/puzzling/puzzlingaos/di/ExampleModule.kt
  app/src/main/java/com/puzzling/puzzlingaos/di/Qualifier.kt
  app/src/main/java/com/puzzling/puzzlingaos/di/RepositoryModule.kt
  app/src/main/java/com/puzzling/puzzlingaos/di/RetrofitModule.kt
  app/src/main/java/com/puzzling/puzzlingaos/domain/entity/ActionPlan.kt
  app/src/main/java/com/puzzling/puzzlingaos/domain/entity/MyPuzzleBoard.kt
  app/src/main/java/com/puzzling/puzzlingaos/domain/entity/Project.kt
  app/src/main/java/com/puzzling/puzzlingaos/domain/entity/Puzzle.kt
  app/src/main/java/com/puzzling/puzzlingaos/domain/entity/UserPuzzleBoard.kt
  app/src/main/java/com/puzzling/puzzlingaos/domain/repository/MyBoardRepository.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/HomeFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/personal/MyPuzzleBoardActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/personal/PersonalDashboardFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/personal/PersonalDashboardViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/team/TeamDashboardFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/team/TeamPuzzleBoardActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/main/MainActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/ChooseRetrospectiveFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/WriteRetrospectiveViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/util/JsonObject.kt
  app/src/main/res/drawable/selector_custom_button.xml
  app/src/main/res/layout/fragment_choose_retrospective.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_personal_dashboard.xml
  app/src/main/res/layout/fragment_team_dashboard.xml
  app/src/main/res/values/strings.xml
Labels: 지영🥭

#35 [FEAT] 팀원 현황 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/puzzling/puzzlingaos/data/model/response/ResponseTeamRetrospectListDto.kt
  app/src/main/java/com/puzzling/puzzlingaos/data/repository/TeamCurrentSituationRepositoryImpl.kt
  app/src/main/java/com/puzzling/puzzlingaos/data/source/remote/TeamCurrentSituationRemoteDataSource.kt
  app/src/main/java/com/puzzling/puzzlingaos/domain/entity/TeamRetrospectList.kt
  app/src/main/java/com/puzzling/puzzlingaos/domain/entity/TeamRetrospectMultiList.kt
  app/src/main/java/com/puzzling/puzzlingaos/domain/entity/ThisWeek.kt
  app/src/main/java/com/puzzling/puzzlingaos/domain/repository/TeamCurrentSituationRepository.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/team/currentSituation/ItemTeamRetrospectListFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/team/currentSituation/MjTestActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/team/currentSituation/NoItemTeamRetrospectListFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/team/currentSituation/RetrospectListAdapter.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/team/currentSituation/RetrospectThisWeekAdapter.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/team/currentSituation/TeamCurrentSituationFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/team/currentSituation/TeamCurrentSituationViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/util/ViewModelFactory.kt
  app/src/main/res/drawable/round_blue100_fill.xml
  app/src/main/res/drawable/round_blue400_fill.xml
  app/src/main/res/drawable/round_white_fill.xml
  app/src/main/res/layout/activity_mj_test.xml
  app/src/main/res/layout/fragment_item_team_retrospect_list.xml
  app/src/main/res/layout/fragment_no_item_team_retrospect_list.xml
  app/src/main/res/layout/fragment_team_current_situation.xml
  app/src/main/res/layout/item_team_do_retrospect_list.xml
  app/src/main/res/layout/item_team_do_retrospect_text.xml
  app/src/main/res/layout/item_team_dont_retrospect_list.xml
  app/src/main/res/layout/item_team_dont_retrospect_text.xml
  app/src/main/res/layout/item_team_this_week.xml
Labels: 민정🍑

#52 [FIX/#50] mvvm git 충돌 해결
  app/src/main/java/com/puzzling/puzzlingaos/di/ApiModule.kt
  app/src/main/java/com/puzzling/puzzlingaos/di/DataSourceModule.kt
  app/src/main/java/com/puzzling/puzzlingaos/di/RepositoryModule.kt
  app/src/main/java/com/puzzling/puzzlingaos/util/ViewModelFactory.kt
Labels: 가은🍊

#54 [FEAT] 프로젝트 등록 뷰 상세화
  app/src/main/java/com/puzzling/puzzlingaos/data/model/response/ResponseProjectRegisterDto.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/register/RegisterActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/register/RetrospectWeekCycleAdapter.kt
  app/src/main/res/drawable/bg_button_selected_ripple.xml
  app/src/main/res/drawable/ic_register_toolbar_close.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/fragment_projectcode_dialog.xml
  app/src/main/res/layout/item_register_retrospect_week_cycle.xml
Labels: 민정🍑

#58 Hotfix/inflate issue
  app/src/main/java/com/puzzling/puzzlingaos/data/model/request/RequestInvitationCode.kt
  app/src/main/java/com/puzzling/puzzlingaos/data/model/response/ResponseProjectRetroWeekDto.kt
  app/src/main/java/com/puzzling/puzzlingaos/data/repository/ProjectRepositoryImpl.kt
  app/src/main/java/com/puzzling/puzzlingaos/data/service/ProjectService.kt
  app/src/main/java/com/puzzling/puzzlingaos/data/source/remote/ProjectDataSource.kt
  app/src/main/java/com/puzzling/puzzlingaos/data/source/remote/impl/ProjectDataSourceImpl.kt
  app/src/main/java/com/puzzling/puzzlingaos/domain/repository/ProjectRepository.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/HomeViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/invitationCode/InputCodeFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/invitationCode/InputProfileFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/invitationCode/InvitationCodeActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/invitationCode/InvitationCodeViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/mypage/MyRetrospectViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/util/ViewModelFactory.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_input_code.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
Labels: 가은🍊

#66 [FIX] 전체 UI 수정
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/puzzling/puzzlingaos/di/RetrofitModule.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/detailRetrospect/DetailRetroViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/HomeFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/HomeViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/invitationCode/InvitationCodeActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/invitationCode/InvitationCodeViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/mypage/MyRetrospectViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/mypage/adapter/MyProjectTitleAdapter.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/register/RegisterActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/util/Constants.kt
  app/src/main/res/layout/activity_choose_join_register.xml
  app/src/main/res/layout/activity_detail_retro.xml
  app/src/main/res/layout/activity_invitation_code.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_my_retrospect.xml
Labels: 가은🍊

#69 [FEAT] 팀원 현황 뷰 UI 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/puzzling/puzzlingaos/presentation/team/currentSituation/ItemTeamRetrospectListFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/team/currentSituation/MjTestActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/team/currentSituation/RetrospectThisWeekAdapter.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/team/currentSituation/TeamCurrentSituationViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/team/currentSituation/TeamRetroActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/team/currentSituation/TeamRetroViewModel.kt
  app/src/main/res/layout/activity_mj_test.xml
  app/src/main/res/layout/activity_team_retro.xml
  app/src/main/res/layout/fragment_item_team_retrospect_list.xml
  app/src/main/res/layout/item_team_do_retrospect_list.xml
  app/src/main/res/layout/item_team_dont_retrospect_list.xml
  app/src/main/res/layout/item_team_dont_retrospect_text.xml
Labels: 민정🍑

#70 [FIX] 홈 UI 수정
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/puzzling/puzzlingaos/data/model/response/ResponseSaveReviewDto.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/HomeViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/personal/ActionPlanListAdapter.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/personal/MyPuzzleBoardActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/personal/MyPuzzleBoardAdapter.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/personal/MyPuzzleBoardViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/personal/PersonalDashboardFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/personal/PersonalDashboardViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/personal/puzzleboard/OnePuzzleBoardActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/personal/puzzleboard/ThreePuzzleBoardActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/personal/puzzleboard/TwoPuzzleBoardActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/team/TeamDashBoardViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/team/TeamDashboardFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/team/TeamPuzzleBoardActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/team/TeamPuzzleBoardAdapter.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/team/TeamPuzzleBoardViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/team/puzzleboard/OneTeamBoardActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/team/puzzleboard/ThreeTeamBoardActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/team/puzzleboard/TwoTeamBoardActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/RegisterDialogFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/WriteRetrospectiveActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/WriteReviewViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/util/Constants.kt
  app/src/main/res/layout/activity_one_puzzle_board.xml
  app/src/main/res/layout/activity_one_team_board.xml
  app/src/main/res/layout/activity_three_puzzle_board.xml
  app/src/main/res/layout/activity_three_team_board.xml
  app/src/main/res/layout/activity_two_puzzle_board.xml
  app/src/main/res/layout/activity_two_team_board.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_personal_dashboard.xml
  app/src/main/res/layout/fragment_register_dialog.xml
  app/src/main/res/layout/fragment_team_dashboard.xml
  app/src/main/res/layout/item_home_actionplan.xml
  app/src/main/res/values/strings.xml
Labels: 지영🥭

#75 [FIX] UI 뷰 수정
  app/src/main/java/com/puzzling/puzzlingaos/domain/entity/ActionPlan.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/detailRetrospect/DetailRetroActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/HomeFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/personal/PersonalDashboardViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/team/TeamDashboardFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/ChooseReviewFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/RegisterDialogFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/WriteRetrospectiveActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/WriteReviewViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/util/CustomSnackbar.kt
  app/src/main/java/com/puzzling/puzzlingaos/util/ViewExt.kt
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/layout/activity_detail_retro.xml
  app/src/main/res/layout/activity_write_retrospective.xml
  app/src/main/res/layout/fragment_choose_review.xml
  app/src/main/res/layout/fragment_write5f.xml
  app/src/main/res/layout/fragment_write_aar.xml
  app/src/main/res/layout/fragment_write_til.xml
  app/src/main/res/layout/snackbar_custom.xml
Labels: 지영🥭

#76 [FEAT] 팀원 현황 뷰 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/personal/PersonalDashboardFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/team/currentSituation/TeamRetroActivity.kt
Labels: 민정🍑

#80 [FEAT] 프로젝트 등록 뷰 수정
  app/src/main/java/com/puzzling/puzzlingaos/presentation/register/RegisterActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/register/RegisterViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/register/projectCode/ProjectCodeDialogFragment.kt
Labels: 민정🍑

#85 [FEAT] UI 수정
  app/src/main/java/com/puzzling/puzzlingaos/presentation/team/currentSituation/TeamRetroActivity.kt
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/values/strings.xml
Labels: 민정🍑

#87 [FIX] 대대적인 로직 수정
  app/src/main/java/com/puzzling/puzzlingaos/presentation/detailRetrospect/DetailRetroActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/HomeFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/HomeViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/personal/PersonalDashboardFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/personal/PersonalDashboardViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/team/TeamDashBoardViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/team/TeamDashboardFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/invitationCode/InvitationCodeViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/main/MainActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/team/currentSituation/TeamRetroActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/RegisterDialogFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/Write5fFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/WriteRetrospectiveActivity.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/WriteReviewViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/util/Constants.kt
  app/src/main/res/layout/fragment_personal_dashboard.xml
Labels: 지영🥭
