Repository Team-Puzzling/Puzzling_Android, pull requests merged in 2023-08, with the labels that each got.

#90 [FEAT] 개인/팀 대시보드 조회 api 수정
  app/src/main/java/com/puzzling/puzzlingaos/data/model/response/ResponseMyPuzzleBoardDto.kt
  app/src/main/java/com/puzzling/puzzlingaos/data/model/response/ResponseTeamPuzzleBoardDto.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/home/team/TeamDashboardFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/register/projectCode/ProjectCodeDialogFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/writeRetrospective/RegisterDialogFragment.kt
  app/src/main/res/layout/fragment_team_dashboard.xml
Labels: 지영🥭

#93 [REFACTOR] 팀원 회고 조회 DTO 수정
  app/src/main/java/com/puzzling/puzzlingaos/data/model/response/ResponseTeamReviewListDto.kt
Labels: 민정🍑

#94 [REFACTOR] 기타 작업 수정
  app/src/main/java/com/puzzling/puzzlingaos/data/model/response/ResponseDetailRetroDto.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/detailRetrospect/DetailRetroAdapter.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/detailRetrospect/DetailRetroViewModel.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/invitationCode/InputCodeFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/invitationCode/InputProfileFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/mypage/ChooseProjectBottomFragment.kt
  app/src/main/java/com/puzzling/puzzlingaos/presentation/mypage/adapter/ChooseProjectAdapter.kt
Labels: 가은🍊

#97 [FIX] DTO 관련 오류 수정
  app/src/main/java/com/puzzling/puzzlingaos/presentation/team/currentSituation/TeamRetroViewModel.kt
Labels: 민정🍑
